implemented super rotation system

diff --git a/tetris b/tetris
--- a/tetris
+++ b/tetris
@@ -16,7 +16,7 @@
 # * Score System
 # * Variable Goal System
 # * Classic Lock Down
-# * Classic Rotation System
+# * Super/Classic Rotation System
 # * Changing the Starting Level 
 # 
 # not implemented
@@ -24,7 +24,6 @@
 # * T-Spin / Mini T-Spin
 # * Ghost Piece
 # * Back-to-Back Bonus
-# * Super Rotation System 
 # * Extended Placement Lock Down
 # * Infinite Placement Lock Down
 # 
@@ -183,55 +182,89 @@ START_Y=21
 # this array holds all possible pieces that can be used in the game
 # each piece consists of 4 cells(minos)
 # each string is sequence of relative xy coordinates
+# Format:
+#   piece_<TETRIMINO>_minos_<FACING>='<mino_0_x> <mino_1_y> ...'
+#   
+#   piece_<TETRIMINO>_rchifts_<FACING>='<POINT_1> <POINT_2> ...'
+#     <POINT_<NO>>: <ROTATION_LEFT_shifts> <ROTATION_RIGHT_shifts>
+#     <ROTATION_<DIR>_shifts>: <shift_x> <shift_y>
 
 # O-Tetrimino
 eval piece_"$O_TETRIMINO"_color=\"$YELLOW\"
 eval piece_"$O_TETRIMINO"_minos_"$NORTH"=\'1 0 2 0 1 1 2 1\'
-eval piece_"$O_TETRIMINO"_minos_"$EAST"=\'1 0 2 0 1 1 2 1\'
+eval piece_"$O_TETRIMINO"_minos_"$EAST"=\' 1 0 2 0 1 1 2 1\'
 eval piece_"$O_TETRIMINO"_minos_"$SOUTH"=\'1 0 2 0 1 1 2 1\'
-eval piece_"$O_TETRIMINO"_minos_"$WEST"=\'1 0 2 0 1 1 2 1\'
+eval piece_"$O_TETRIMINO"_minos_"$WEST"=\' 1 0 2 0 1 1 2 1\'
+eval piece_"$O_TETRIMINO"_rshifts_"$NORTH"=\"0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0\"
+eval piece_"$O_TETRIMINO"_rshifts_"$EAST"=\" 0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0\"
+eval piece_"$O_TETRIMINO"_rshifts_"$SOUTH"=\"0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0\"
+eval piece_"$O_TETRIMINO"_rshifts_"$WEST"=\" 0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0   0  0  0  0\"
 
 # I-Tetrimino
 eval piece_"$I_TETRIMINO"_color=\"$CYAN\"
 eval piece_"$I_TETRIMINO"_minos_"$NORTH"=\'0 1 1 1 2 1 3 1\'
-eval piece_"$I_TETRIMINO"_minos_"$EAST"=\'2 0 2 1 2 2 2 3\'
+eval piece_"$I_TETRIMINO"_minos_"$EAST"=\' 2 0 2 1 2 2 2 3\'
 eval piece_"$I_TETRIMINO"_minos_"$SOUTH"=\'0 2 1 2 2 2 3 2\'
-eval piece_"$I_TETRIMINO"_minos_"$WEST"=\'1 0 1 1 1 2 1 3\'
+eval piece_"$I_TETRIMINO"_minos_"$WEST"=\' 1 0 1 1 1 2 1 3\'
+eval piece_"$I_TETRIMINO"_rshifts_"$NORTH"=\"0  0  0  0  -1  0 -2  0   2  0  1  0  -1  2 -2 -1   2 -1  1  2\"
+eval piece_"$I_TETRIMINO"_rshifts_"$EAST"=\" 0  0  0  0   2  0 -1  0  -1  0  2  0   2  1 -1  2  -1 -2  2 -1\"
+eval piece_"$I_TETRIMINO"_rshifts_"$SOUTH"=\"0  0  0  0   1  0  2  0  -2  0 -1  0   1 -2  2  1  -2  1 -1 -2\"
+eval piece_"$I_TETRIMINO"_rshifts_"$WEST"=\" 0  0  0  0  -2  0  1  0   1  0 -2  0  -2 -1  1 -2   1  2 -2  1\"
 
 # T-Tetrimino
 eval piece_"$T_TETRIMINO"_color=\"$MAGENTA\"
 eval piece_"$T_TETRIMINO"_minos_"$NORTH"=\'1 0 0 1 1 1 2 1\'
-eval piece_"$T_TETRIMINO"_minos_"$EAST"=\'1 0 1 1 2 1 1 2\'
+eval piece_"$T_TETRIMINO"_minos_"$EAST"=\' 1 0 1 1 2 1 1 2\'
 eval piece_"$T_TETRIMINO"_minos_"$SOUTH"=\'0 1 1 1 2 1 1 2\'
-eval piece_"$T_TETRIMINO"_minos_"$WEST"=\'1 0 0 1 1 1 1 2\'
+eval piece_"$T_TETRIMINO"_minos_"$WEST"=\' 1 0 0 1 1 1 1 2\'
+eval piece_"$T_TETRIMINO"_rshifts_"$NORTH"=\"0  0  0  0   1  0 -1  0   1  1 -1  1   n  n  n  n   1 -2 -1 -2\"
+eval piece_"$T_TETRIMINO"_rshifts_"$EAST"=\" 0  0  0  0   1  0  1  0   1 -1  1 -1   0  2  0  2   1  2  1  2\"
+eval piece_"$T_TETRIMINO"_rshifts_"$SOUTH"=\"0  0  0  0  -1  0  1  0   n  n  n  n   0 -2  0 -2  -1 -2  1 -2\"
+eval piece_"$T_TETRIMINO"_rshifts_"$WEST"=\" 0  0  0  0  -1  0 -1  0  -1 -1 -1 -1   0  2  0  2  -1  2 -1  2\"
 
 # L-Tetrimino
 eval piece_"$L_TETRIMINO"_color=\"$ORANGE\"
 eval piece_"$L_TETRIMINO"_minos_"$NORTH"=\'2 0 0 1 1 1 2 1\'
-eval piece_"$L_TETRIMINO"_minos_"$EAST"=\'1 0 1 1 1 2 2 2\'
+eval piece_"$L_TETRIMINO"_minos_"$EAST"=\' 1 0 1 1 1 2 2 2\'
 eval piece_"$L_TETRIMINO"_minos_"$SOUTH"=\'0 1 1 1 2 1 0 2\'
-eval piece_"$L_TETRIMINO"_minos_"$WEST"=\'0 0 1 0 1 1 1 2\'
+eval piece_"$L_TETRIMINO"_minos_"$WEST"=\' 0 0 1 0 1 1 1 2\'
+eval piece_"$L_TETRIMINO"_rshifts_"$NORTH"=\"0  0  0  0   1  0 -1  0   1  1 -1  1   0 -2  0 -2   1 -2 -1 -2\"
+eval piece_"$L_TETRIMINO"_rshifts_"$EAST"=\" 0  0  0  0   1  0  1  0   1 -1  1 -1   0  2  0  2   1  2  1  2\"
+eval piece_"$L_TETRIMINO"_rshifts_"$SOUTH"=\"0  0  0  0  -1  0  1  0  -1  1  1  1   0 -2  0 -2  -1 -2  1 -2\"
+eval piece_"$L_TETRIMINO"_rshifts_"$WEST"=\" 0  0  0  0  -1  0 -1  0  -1 -1 -1 -1   0  2  0  2  -1  2 -1  2\"
 
 # J-Tetrimino
 eval piece_"$J_TETRIMINO"_color=\"$BLUE\"
 eval piece_"$J_TETRIMINO"_minos_"$NORTH"=\'0 0 0 1 1 1 2 1\'
-eval piece_"$J_TETRIMINO"_minos_"$EAST"=\'1 0 2 0 1 1 1 2\'
+eval piece_"$J_TETRIMINO"_minos_"$EAST"=\' 1 0 2 0 1 1 1 2\'
 eval piece_"$J_TETRIMINO"_minos_"$SOUTH"=\'0 1 1 1 2 1 2 2\'
-eval piece_"$J_TETRIMINO"_minos_"$WEST"=\'1 0 1 1 0 2 1 2\'
+eval piece_"$J_TETRIMINO"_minos_"$WEST"=\' 1 0 1 1 0 2 1 2\'
+eval piece_"$J_TETRIMINO"_rshifts_"$NORTH"=\"0  0  0  0   1  0 -1  0   1  1 -1  1   0 -2  0 -2   1 -2 -1 -2\"
+eval piece_"$J_TETRIMINO"_rshifts_"$EAST"=\" 0  0  0  0   1  0  1  0   1 -1  1 -1   0  2  0  2   1  2  1  2\"
+eval piece_"$J_TETRIMINO"_rshifts_"$SOUTH"=\"0  0  0  0  -1  0  1  0  -1  1  1  1   0 -2  0 -2  -1 -2  1 -2\"
+eval piece_"$J_TETRIMINO"_rshifts_"$WEST"=\" 0  0  0  0  -1  0 -1  0  -1 -1 -1 -1   0  2  0  2  -1  2 -1  2\"
 
 # S-Tetrimino
 eval piece_"$S_TETRIMINO"_color=\"$GREEN\"
 eval piece_"$S_TETRIMINO"_minos_"$NORTH"=\'1 0 2 0 0 1 1 1\'
-eval piece_"$S_TETRIMINO"_minos_"$EAST"=\'1 0 1 1 2 1 2 2\'
+eval piece_"$S_TETRIMINO"_minos_"$EAST"=\' 1 0 1 1 2 1 2 2\'
 eval piece_"$S_TETRIMINO"_minos_"$SOUTH"=\'1 1 2 1 0 2 1 2\'
-eval piece_"$S_TETRIMINO"_minos_"$WEST"=\'0 0 0 1 1 1 1 2\'
+eval piece_"$S_TETRIMINO"_minos_"$WEST"=\' 0 0 0 1 1 1 1 2\'
+eval piece_"$S_TETRIMINO"_rshifts_"$NORTH"=\"0  0  0  0   1  0 -1  0   1  1 -1  1   0 -2  0 -2   1 -2 -1 -2\"
+eval piece_"$S_TETRIMINO"_rshifts_"$EAST"=\" 0  0  0  0   1  0  1  0   1 -1  1 -1   0  2  0  2   1  2  1  2\"
+eval piece_"$S_TETRIMINO"_rshifts_"$SOUTH"=\"0  0  0  0  -1  0  1  0  -1  1  1  1   0 -2  0 -2  -1 -2  1 -2\"
+eval piece_"$S_TETRIMINO"_rshifts_"$WEST"=\" 0  0  0  0  -1  0 -1  0  -1 -1 -1 -1   0  2  0  2  -1  2 -1  2\"
 
 # Z-Tetrimino
 eval piece_"$Z_TETRIMINO"_color=\"$RED\"
 eval piece_"$Z_TETRIMINO"_minos_"$NORTH"=\"0 0 1 0 1 1 2 1\"
-eval piece_"$Z_TETRIMINO"_minos_"$EAST"=\"2 0 1 1 2 1 1 2\"
+eval piece_"$Z_TETRIMINO"_minos_"$EAST"=\" 2 0 1 1 2 1 1 2\"
 eval piece_"$Z_TETRIMINO"_minos_"$SOUTH"=\"0 1 1 1 1 2 2 2\"
-eval piece_"$Z_TETRIMINO"_minos_"$WEST"=\"1 0 0 1 1 1 0 2\"
+eval piece_"$Z_TETRIMINO"_minos_"$WEST"=\" 1 0 0 1 1 1 0 2\"
+eval piece_"$Z_TETRIMINO"_rshifts_"$NORTH"=\"0  0  0  0   1  0 -1  0   1  1 -1  1   0 -2  0 -2   1 -2 -1 -2\"
+eval piece_"$Z_TETRIMINO"_rshifts_"$EAST"=\" 0  0  0  0   1  0  1  0   1 -1  1 -1   0  2  0  2   1  2  1  2\"
+eval piece_"$Z_TETRIMINO"_rshifts_"$SOUTH"=\"0  0  0  0  -1  0  1  0  -1  1  1  1   0 -2  0 -2  -1 -2  1 -2\"
+eval piece_"$Z_TETRIMINO"_rshifts_"$WEST"=\" 0  0  0  0  -1  0 -1  0  -1 -1 -1 -1   0  2  0  2  -1  2 -1  2\"
 
 help='
 ←         Move Left or Right
@@ -251,9 +284,12 @@ usage="
 Usage: ${0##*/} [options]
 
 Options:
- -d, --debug  debug mode
- -l, --level  game level. range from 1 to $LEVEL_MAX
- -h, --help   display this help and exit
+ -d, --debug            debug mode
+ -l, --level <LEVEL>    game level (default=1). range from 1 to $LEVEL_MAX
+ -r, --rotation <MODE>  use 'Super' or 'Classic' rotation system
+                        MODE can be 'super'(default) or 'classic'
+
+ -h, --help  display this help and exit
 
 Version:
  $VERSION
@@ -559,7 +595,7 @@ draw_piece() {
   shift $#
 
   # set minos coordinates.
-  set $(eval echo \"\$piece_"$type"_minos_"$rotation"\")
+  eval set \$piece_"$type"_minos_"$rotation"
 
   # loop through tetrimino minos: 4 minos, each has 2 coordinates
   while [ $# -gt 0 ]; do
@@ -664,7 +700,7 @@ new_piece_location_ok() {
 
   # set minos coordinates into parameters
   # $1 - x, $2 - y
-  set $(eval echo \"\$piece_"$current_piece"_minos_"$current_piece_rotation"\")
+  eval set \$piece_"$current_piece"_minos_"$current_piece_rotation"
   
   # loop through tetrimino minos: 4 minos, each has 2 coordinates
   while [ $# -gt 0 ]; do
@@ -724,7 +760,7 @@ flatten_playfield() {
 
   # set minos coordinates into parameters
   # $1 - x, $2 - y
-  set $(eval echo \"\$piece_"$current_piece"_minos_"$current_piece_rotation"\")
+  eval set \$piece_"$current_piece"_minos_"$current_piece_rotation"
   
   # loop through tetrimino minos: 4 minos, each has 2 coordinates
   while [ $# -gt 0 ]; do
@@ -855,7 +891,7 @@ lockdown() {
   already_hold=false   # player can hold the falling tetrimino.
 }
 
-rotate_piece() {
+rotate_piece_classic() {
   # arguments: 1 - rotation direction; 1: clockwise; -1: counter-clockwise
   local direction="$1" old_rotation new_rotation
   
@@ -871,6 +907,47 @@ rotate_piece() {
   else                                                             # if new orientation is not ok
     current_piece_rotation=$old_rotation                           # restore old orientation
   fi
+}
+
+rotate_piece_super() {
+  # arguments: 1 - rotation direction. 1: clockwise; -1: counter-clockwise
+  local direction="$1" old_rotation new_rotation shift_x shift_y new_x new_y
+  
+  old_rotation=$current_piece_rotation # preserve current orientation
+
+  new_rotation=$((old_rotation + direction + 4)) #
+  new_rotation=$((new_rotation % 4))             # calculate new orientation
+
+  current_piece_rotation=$new_rotation
+
+  # test each rotation point. Each Tetrimino has five possible rotation points. 
+  shift $#
+  eval set \$piece_${current_piece}_rshifts_${old_rotation}
+  # now parameters setted like below
+  # '<POINT1> <POINT2> <POINT3> <POINT4> <POINT5>'
+  #   <POINT<NO>>: '<LEFT_SHIFT_X> <LEFT_SHIFT_Y> <RIGHT_SHIFT_X> <RIGHT_SHIFT_Y>'
+  while [ $# -gt 0 ]; do
+    [ $1 = 'n' ] && { shift 4; continue; } # if 'not used' appears, skip this point
+    [ $direction -eq 1 ] && shift 2        # if rotate clockwise(RIGHT) shift 2 to next xy-coordinates of RIGHT
+
+    shift_x=$1; shift_y=$2
+    new_x=$((current_piece_x + shift_x))
+    new_y=$((current_piece_y + shift_y))
+    if new_piece_location_ok $new_x $new_y; then # check if new orientation is ok
+      current_piece_rotation=$old_rotation       # if yes - restore old rotation ...
+      clear_current                              # ... clear piece image
+      current_piece_rotation=$new_rotation       # ... set new orientation
+      current_piece_x=$new_x                     # ... set new location
+      current_piece_y=$new_y                     #
+      show_current                               # ... draw piece with new pose
+      return                                     # nothing to do more here
+    fi
+    
+    shift 2 # test next rotation point
+  done
+
+  # if new orientation is not ok
+  current_piece_rotation=$old_rotation # restore old orientation
 }
 
 draw_help() {
@@ -952,11 +1029,11 @@ hard_drop() {
 }
 
 rotate_cw() {
-  rotate_piece 1
+  $rotate_piece_func 1
 }
 
 rotate_ccw() {
-  rotate_piece -1
+  $rotate_piece_func -1
 }
 
 hold() {
@@ -1194,6 +1271,7 @@ main() {
     --help|-h) print_usage_and_exit;;
   esac
 
+  rotate_piece_func=rotate_piece_super
   starting_level=1
   debug=false
   while [ $# -gt 0 ]; do
@@ -1206,13 +1284,29 @@ main() {
         [ $# -le 1 ]                                    || # if next parameter not exists...
         { expr $2 + 1 > /dev/null 2>&1; [ $? -gt 1 ]; } || # ...not number
         [ $2 -lt 1 ]                                    || # ...less than 1
-        [ $2 -gt $LEVEL_MAX ]                           && # ...greater than LEVEL_MAX
-        print_usage_and_exit                               # then exit
+        [ $2 -gt $LEVEL_MAX ]                           && # ...greater than LEVEL_MAX, then exit
+        {
+          echo "${0##*/}: invalid level '$2'" 1>&2
+          print_usage_and_exit
+        }
 
         starting_level=$2
         shift 2; continue
         ;;
+      -r|--rotation)
+        [ $# -le 1 ] && print_usage_and_exit
+        case $2 in
+          classic) rotate_piece_func=rotate_piece_classic ;;
+          super)   rotate_piece_func=rotate_piece_super   ;;
+          *)
+            echo "${0##*/}: unrecognized rotation mode '$2'" 1>&2
+            print_usage_and_exit
+            ;;
+        esac
+        shift 2; continue
+        ;;
       *)
+        echo "${0##*/}: unrecognized option '$1'" 1>&2
         print_usage_and_exit
         ;;
     esac
